### PR TITLE
W-13065369: User Story B - Integration of Optel metrics exporter and …

### PR DESCRIPTION
**Pull request by fsgonz**
…mule runtime tracer for AllStatistics metrics

### CODE REVIEW

**Comment by fsgonz** [comment]
--validate

**Comment by fsgonz** [comment]
--validate

**Comment by fsgonz** [comment]
--validate

**Comment by fsgonz** [comment]
--validate

**Comment by fsgonz** [comment]
--validate

**Comment by fsgonz** [comment]
--validate

**Review by IvanAndresFritzler — APPROVED** [review]

**Pull request merged**
