### PR TITLE
W-13066872: Update assembly-allowlist to include mule-jar-handling-tils.jar

### PR DESCRIPTION
**Pull request by mule-pachanady**

### CODE REVIEW

**Review by elrodro83 — APPROVED** [review]

**Review by elrodro83 — CHANGES_REQUESTED** [review]

**Review by elrodro83 — DISMISSED** [review]

**Comment by mule-pachanady** [comment]
--validate

**Comment by mule-pachanady** [comment]
@elrodro83 Had to add entry in assembly.xml as it was not building distn due new jar

**Review by elrodro83 — APPROVED** [review]

**Comment by mule-pachanady** [comment]
--validate

**Comment by mule-pachanady** [comment]
--validate

**Pull request merged**
